// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnk8H1v5val8TizUVUn1Q1-TtbhwX_KlQ',
    appId: '1:531599313108:web:de60bd6f3f5dc6309dd341',
    messagingSenderId: '531599313108',
    projectId: 'expiry-ce907',
    authDomain: 'expiry-ce907.firebaseapp.com',
    storageBucket: 'expiry-ce907.appspot.com',
    measurementId: 'G-CT320DQX2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiWH1ffJ6Dl8KGYVagyVR4GemKOZdRsjA',
    appId: '1:531599313108:android:9222877bc84d455e9dd341',
    messagingSenderId: '531599313108',
    projectId: 'expiry-ce907',
    storageBucket: 'expiry-ce907.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFyeNkNrKFNz2U7kE8ylgtohhsQkkN8lU',
    appId: '1:531599313108:ios:ac133bf56d0f154e9dd341',
    messagingSenderId: '531599313108',
    projectId: 'expiry-ce907',
    storageBucket: 'expiry-ce907.appspot.com',
    iosClientId: '531599313108-bpma46rpvj2f4tmsnv4iffa3ok009cvo.apps.googleusercontent.com',
    iosBundleId: 'com.example.expiry',
  );
}
